### Task 16 - Numpy Basics:


#### 1. Describe the features of numpy.


NumPy (Numerical Python) is a powerful library for numerical computing in Python.

It has features that make it essential for tasks involving mathematical operations, data analysis, and scientific computing. 

Here are some key features:

- **Multi-dimensional Arrays:** NumPy provides the ndarray (N-dimensional array) object, which allows efficient storage and manipulation of large datasets in a grid-like structure.
- **Mathematical Functions:** It includes a wide array of built-in mathematical functions for operations like linear algebra, Fourier transforms, statistical analysis, and more.
- **Broadcasting:** This feature enables operations on arrays of different shapes, simplifying tasks without requiring explicit reshaping.
- **Performance:** NumPy is highly optimized for speed, making operations faster than native Python lists.
- **Indexing and Slicing:** Powerful tools to access or modify subsets of data in arrays.
- **Integration:** Compatible with other scientific computing libraries like SciPy, pandas, and matplotlib, making it ideal for broader workflows.
- **Random Sampling:** Contains robust tools for generating random numbers and working with probabilistic methods.
- **Universal Functions (ufuncs):** These perform element-wise operations on arrays, enabling quick computations.


#### 2. Write the applications of numpy.


1. **Scientific Computing** – NumPy is essential for handling complex mathematical operations, linear algebra, and array manipulation, making it invaluable in scientific research.
2. **Data Analysis** – Many data science libraries like Pandas rely on NumPy for efficient data processing.
3. **Machine Learning** – Frameworks like TensorFlow and Scikit-learn use NumPy arrays for numerical computations.
4. **Image Processing** – NumPy helps manipulate pixel values in images, forming the backbone of many image-processing tasks.
5. **Signal Processing** – Filtering and analyzing signals, such as audio and sensor data, often leverage NumPy's mathematical capabilities.
6. **Statistical Analysis** – Researchers use NumPy for probability distributions, hypothesis testing, and other statistical computations.
7. **Physics and Engineering Simulations** – NumPy is used in simulations involving fluid dynamics, mechanical systems, and electronic circuits.
8. **Financial Modeling** – Analysts use NumPy for risk assessment, predictive modeling, and portfolio management.
9. **Graph and Network Analysis** – NumPy aids in the study of network structures, social networks, and graph-based algorithms.


#### 3. How numpy is different from python sequences.


NumPy arrays and Python sequences (like lists and tuples) have fundamental differences that make NumPy more suitable for numerical computing:

1. **Performance** – NumPy arrays are significantly faster than Python lists due to their optimized C-based implementation.
2. **Memory Efficiency** – NumPy stores data in a contiguous block of memory, unlike Python lists, which store references to objects, making NumPy more memory-efficient.
3. **Vectorized Operations** – NumPy allows element-wise arithmetic operations without looping, whereas Python lists require explicit iteration.
4. **Data Types** – NumPy enforces a single data type for all elements in an array, whereas Python lists can contain mixed data types.
5. **Functionality** – NumPy provides advanced mathematical functions, linear algebra tools, and random number generation, which Python lists lack.
6. **Multi-Dimensional Support** – While Python lists can be nested to simulate multi-dimensional arrays, NumPy natively supports multi-dimensional arrays with better indexing and manipulation.


#### 4. Create two 1-D arrays with numbers and strings respectively.


In [30]:
import numpy as np
array = np.array([12, 45, 67, 86, -98])
print(array)
print(type(array))
print(array.ndim)
print(array.shape)
print(array.size)

array1 = np.array(['A','B','C','D','E','F'])
print(array1)
print(type(array1))
print(array1.ndim)
print(array1.shape)
print(array1.size)


[ 12  45  67  86 -98]
<class 'numpy.ndarray'>
1
(5,)
5
['A' 'B' 'C' 'D' 'E' 'F']
<class 'numpy.ndarray'>
1
(6,)
6


#### 5. Create 2-D and 3-D arrays. And check their shape and dimensions using (shape and ndim methods).


In [40]:
D_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array :\n", D_array)
print("Dimensions of array : ",D_array.ndim)
print("Shape of array : ",D_array.shape)
print("\n")

D_array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-4,0,1],[6,5,2],[7,9,4]]])
print("3D array :\n", D_array)
print("Dimensions of array : ",D_array.ndim)
print("Shape of array : ",D_array.shape)


2D array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions of array :  2
Shape of array :  (3, 3)


3D array :
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[-4  0  1]
  [ 6  5  2]
  [ 7  9  4]]]
Dimensions of array :  3
Shape of array :  (2, 3, 3)


#### 6. Create a 1D NumPy array with elements from 1 to 10 using arange().


In [50]:
arr = np.arange(1,11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


#### a). Create a 2D array of size 3x3 filled with zeros using zeros().


In [52]:
array = np.zeros((3, 3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 7. Create an array [5, 10, 15, 20, 25]. Find its size.


In [54]:
array = np.array([5, 10, 15, 20, 25])
print("Array : ",array)
print("Size of the array : ",array.size)

Array :  [ 5 10 15 20 25]
Size of the array :  5
