### Task 18 - Numpy Methods:


In [12]:
import numpy as np

#### 1.Create a 1D NumPy array with values from 1 to 10. Access the elements at indices 2, 5, and 7


In [18]:
arr1 = np.arange(1,11)
print(arr1)
arr1[[2,5,7]]

[ 1  2  3  4  5  6  7  8  9 10]


array([3, 6, 8])

#### a)Given an array `arr = np.array([10, 20, 30, 40, 50, 60, 70])`, extract a slice that contains the elements from index 2 to 5.


In [20]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
arr[2:6]

array([30, 40, 50, 60])

#### b)Create an array of 10 random integers between 1 and 20. Extract all elements greater than 10./z


In [50]:
arr = np.random.randint(1,20, size =10)
print("Array : ",arr)
filtered_arr = arr[arr > 10]
print("Elements greater than 10 : ",filtered_arr)

Array :  [12 15 16  6 10  1  3  7 15  5]
Elements greater than 10 :  [12 15 16 15]


#### 2.Create a NumPy array of size 6.  


In [67]:
arr2 = np.array([10,20,30,40,50,60])
arr2

array([10, 20, 30, 40, 50, 60])

#### a)Replace the second element with 99.


In [69]:
arr2[1] = 99
arr2

array([10, 99, 30, 40, 50, 60])

#### b)Update a slice of elements from index 2 to 4 with 0.  


In [73]:
arr2[2:5]=0
arr2

array([10, 99,  0,  0,  0, 60])

#### c)Set the last three elements to 10.  


In [75]:
arr2[-3:]=10
arr2

array([10, 99,  0, 10, 10, 10])

#### 3.Updating a 2D Array  


#### a)Create a 3x3 NumPy array with values from 1 to 9  .


In [86]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### b)Replace the second row with all 5s.  


In [92]:
arr1[1] = 5
arr1

array([[1, 2, 3],
       [5, 5, 5],
       [7, 8, 9]])

#### c)Update the third column with values [8, 9, 10].


In [98]:
arr1[:,2] = [8, 9, 10]
arr1

array([[ 1,  2,  8],
       [ 5,  5,  9],
       [ 7,  8, 10]])

#### 4.Using a Condition to Modify Elements:  


#### a)Create a NumPy array with random numbers from 1 to 20.  


In [114]:
array = np.random.randint(1,20, size=(5,4))
array

array([[18, 19, 10,  2],
       [12, 11, 14,  7],
       [ 9,  9, 11, 18],
       [18, 12, 17,  4],
       [17,  9, 18, 16]])

#### b)Set all values greater than 10 to zero.  


In [118]:
np.where(array > 10,0,array)

array([[ 0,  0, 10,  2],
       [ 0,  0,  0,  7],
       [ 9,  9,  0,  0],
       [ 0,  0,  0,  4],
       [ 0,  9,  0,  0]])

#### 5.Create an array [10, 20, 30, 40] and insert 25 at index 2.  


In [126]:
array = np.array([10, 20, 30, 40])
print("Original array : ",array)
array[2]=25
print("Updated array : ",array)

Original array :  [10 20 30 40]
Updated array :  [10 20 25 40]


#### 6.Create an array [1, 2, 3] and append [4, 5, 6] to it. 


In [134]:
array =np.array([1, 2, 3])
print("Original array : ",array)
updated_array = np.append(array, [4, 5, 6])
print("Updated array : ",updated_array )

Original array :  [1 2 3]
Updated array :  [1 2 3 4 5 6]


#### 7.Create an array [5, 10, 15, 20, 25] and delete the third element.  


In [161]:
array = np.array([5, 10, 15, 20, 25])
print("Original array : ",array)
updated_array = np.delete(array, 2)
print("Updated array : ",updated_array)

Original array :  [ 5 10 15 20 25]
Updated array :  [ 5 10 20 25]


#### 8.Create an array from 1 to 12 and reshape it into a 3×4 matrix.  


In [151]:
array = np.arange(1,13).reshape(3,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### 9.Create a 2D array and flatten it using np.ravel() and .flatten().  


In [153]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

flattened_ravel = np.ravel(array_2d)

flattened_flatten = array_2d.flatten()

print("Original 2D Array:")
print(array_2d)
print("\nFlattened using np.ravel():")
print(flattened_ravel)
print("\nFlattened using .flatten():")
print(flattened_flatten)

Original 2D Array:
[[1 2 3]
 [4 5 6]]

Flattened using np.ravel():
[1 2 3 4 5 6]

Flattened using .flatten():
[1 2 3 4 5 6]


#### 10.Create a 3×3 matrix and find its transpose using np.transpose().


In [171]:
array = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Original array :")
print(array)

transposed_array = np.transpose(array)
print("Updated array : ")
print(transposed_array)

Original array :
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Updated array : 
[[10 40 70]
 [20 50 80]
 [30 60 90]]


#### 11.Create two arrays:  


#### a)A = np.array([2, 4, 6]), B = np.array([1, 2, 3]).  


In [175]:
A = np.array([2, 4, 6])
B = np.array([1, 2, 3])

print("Array A:")
print(A)

print("Array B:")
print(B)

Array A:
[2 4 6]
Array B:
[1 2 3]


#### b)Perform element-wise addition, subtraction, multiplication, and division.  


In [181]:
addition = A + B
print("Addition : \n", addition, "\n")

Subtraction = A - B
print("Subtraction : \n", Subtraction, "\n")

multiplication = A * B
print("multiplication : \n", multiplication, "\n")

division = A / B
print("division : \n", division, "\n")

Addition : 
 [3 6 9] 

Subtraction : 
 [1 2 3] 

multiplication : 
 [ 2  8 18] 

division : 
 [2. 2. 2.] 



#### 12.Create two 2×2 matrices and compute their dot product using np.dot() and @ operator.  


In [197]:
arr1 = np.random.randint(1,10, size =(2,2))
print("arr1 : ")
print(arr1)

arr2 = np.random.randint(10,20, size =(2,2))
print("arr2 : ")
print(arr2)

arr_dot = np.dot(arr1,arr2)
print("dot product of arrays : ")
print(arr_dot)

arr_product = arr1 @ arr2
print("dot product of arrays : ")
print(arr_product)

arr1 : 
[[1 3]
 [7 4]]
arr2 : 
[[10 17]
 [12 16]]
dot product of arrays : 
[[ 46  65]
 [118 183]]
dot product of arrays : 
[[ 46  65]
 [118 183]]


#### 13.Create an array with values [4, 8, 15, 16, 23, 42].  


In [199]:
array = np.array([4, 8, 15, 16, 23, 42])
array

array([ 4,  8, 15, 16, 23, 42])

#### a)Compute sum, min, max, mean, median, variance, standard deviation, and correlation coefficient.



In [212]:
print("Sum of array : ",np.sum(array))
print("Mean of array : ",np.mean(array))
print("Median of array : ",np.median(array))
print("Variance of array : ",np.var(array))
print("Standard deviation of array : ",np.std(array))
print("Correlation coefficient of array : ",np.corrcoef(array))


Sum of array :  108
Mean of array :  18.0
Median of array :  15.5
Variance of array :  151.66666666666666
Standard deviation of array :  12.315302134607444
Correlation coefficient of array :  1.0
