#### Task 17 - Creation of Numpy array using different methods.


In [7]:
import numpy as np

#### 1. Create a 1D NumPy array with elements from 1 to 10 using arange().


In [9]:
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


#### a. Create a 2D array of size 3x3 filled with zeros using zeros().


In [13]:
array1 = np.zeros((3,3))
print(array1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 2. Create an array [5, 10, 15, 20, 25]. Find its size, item size, and total bytes used by the array.


In [22]:
array2 = np.array([5, 10, 15, 20, 25])
print("Array : ", array2)
print("Size of array : ", array2.size)
print("Item Size : ", array2.itemsize)
print("Total bytes used by the array : ", array2.nbytes)

Array :  [ 5 10 15 20 25]
Size of array :  5
Item Size :  4
Total bytes used by the array :  20


#### a. Use linspace() to generate an array of 7 equally spaced numbers between 0 and 14.


In [26]:
array3 = np.linspace(0,14,7)
print(array3)

[ 0.          2.33333333  4.66666667  7.          9.33333333 11.66666667
 14.        ]


#### 3. Create a 4x4 identity matrix using eye().


In [33]:
array4 = np.eye(4)
print(array4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### a. Create a 3x3 diagonal matrix with the diagonal values [1, 2, 3] using diag().


In [35]:
array5 = np.diag([1, 2, 3])
print(array5)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


#### b. Create a 2x3 array filled with the value 9 using full().


In [37]:
array6 = np.full((2,3),9)
print(array6)

[[9 9 9]
 [9 9 9]]


#### 4. Generate a 3x3 array of random numbers between 0 and 1 using random.rand().


In [43]:
array7 = np.random.rand(3,3)
print(array7)

[[0.7811759  0.72075713 0.48532271]
 [0.03911485 0.08223574 0.562116  ]
 [0.02420185 0.96392235 0.84718828]]


#### a. Create a 4x4 array of random integers between 10 and 50 using random.randint().


In [52]:
array7 = np.random.randint(10,50, size = (4,4))
print(array7)

[[24 12 44 29]
 [16 15 18 19]
 [28 46 33 23]
 [17 35 26 44]]


#### b. Generate a 1D array of 5 random numbers from a normal distribution using random.randn().


In [54]:
array8 = np.random.randn(5)
print(array8)

[-0.39363302 -0.8174131  -0.91724268  0.55889491 -0.27849646]


#### c. Generate a 2D array of shape (2, 4) with random values uniformly distributed between -5 and 5 using random.uniform().


In [56]:
array9 = np.random.uniform(-5,5,(2, 4))
print(array9)

[[ 2.95678691 -4.79494762  1.69146862 -0.79202457]
 [ 3.32941137 -4.75999248  3.34126273  3.50664022]]


#### 5. Create a 1D array [10, 20, 30, 40, 50]. Access the third element and update it to 35.


In [77]:
array10 = np.array([10, 20, 30, 40, 50])
print("Original array :",array10)
print("Third element:",array10[2])
array10[2] = 35
print("Updated array:",array10)

Original array : [10 20 30 40 50]
Third element: 30
Updated array: [10 20 35 40 50]


#### a. Create a 2D array of shape (3, 4) with values from 1 to 12. Slice and extract the second row.


In [92]:
array11 = np.arange(1,13).reshape(3, 4)
print("Original array :\n",array11)

print("Second row :\n",array11[1,:])

Original array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row :
 [5 6 7 8]


#### b. From the same array, extract all elements in the last column.


In [96]:
print("Last column :\n",array11[:,-1])

Last column :
 [ 4  8 12]


#### 6. Create a 3x3 array of ones using ones() and change its dtype to int.



In [118]:
array12 = np.ones((3,3))
print("Array :\n",array12)
print("Default datatype :",array12.dtype)
array12.dtype=np.int8
print("Updated datatype :",array12.dtype)

Array :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Default datatype : float64
Updated datatype : int8


#### a. Create an array [1, 2, 3, 4, 5] and multiply each element by 2.



In [120]:
array13 = np.array([1, 2, 3, 4, 5])
print("Array :\n",array13)
res = array13*2
print(res)

Array :
 [1 2 3 4 5]
[ 2  4  6  8 10]
